#!/usr/bin/env python3

import sys

def factoring(n):
    if n % 2 == 0:
        return (int(n / 2), 2)
    for i in range(3, int(n ** 0.5) + 1, 2):
        if n % i == 0:
            return (int(n/i), i)

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: factor <file>")
        sys.exit(1)
    
    file = sys.argv[1]
    with open(file, "r") as nums:
        lines = nums.readlines()

    for line in lines:
        num = int(line.strip())
        if num:
            p, q = factoring(num)
            print(f"{num}={p}*{q}")
