#!/usr/bin/env python3

import sys

def f(x, n):
    r = (x ** 2) % n
    return r

def gcd(a, b):
    while b != 0:
        a, b = b, a % b
    return a

def factor(n):
    x = y = 2
    d = 1

    while d == 1:

        x = f(x, n)
        y = f(f(y, n), n)
        d = gcd(abs(x - y), n)

    if d == n:
        return 2, 2
    return n // d , d

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: factor <file>")
        sys.exit(1)
    
    file = sys.argv[1]
    with open(file, "r") as nums:
        lines = nums.readlines()
    
    res = []
    for line in lines:
        num = int(line.strip())
        if num > 1:
            p, q = factor(num)
            print(f"{num}={p}*{q}")
    res.append(f"{num}={p}*{q}")

    print("\n".join(res))
