#!/usr/bin/env python
import time
import sys

def gcd(a, b):
    while b != 0:
        a, b = b, a % b
    return a
    

def factor(n):
    for i in range(2, int(n ** 0.5 - 1)):
        if gcd(i , n) > 1:
            return n // i, i
    return 2, 2


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: factor <file>")
        sys.exit(1)
    
    file = sys.argv[1]
    with open(file, "r") as nums:
        lines = nums.readlines()

    for line in lines:
        num = int(line.strip())
        if num:
            p, q = factor(num)
            print(f"{num}={p}*{q}")
    print(time.process_time())